insert into Company (CompID, CompName, PostalCode, username) values (1, 'Gibson Group', 'J0T 2P0', 'loffiler0');
insert into Company (CompID, CompName, PostalCode, username) values (2, 'Cole-Emard', 'J7V 3C3', 'lebertz1');
insert into Company (CompID, CompName, PostalCode, username) values (3, 'Cole, Ruecker and West', 'J0X 3E0', 'wcasazza2');
insert into Company (CompID, CompName, PostalCode, username) values (4, 'Spencer, Hettinger and Cassin', 'G0R 3W0', 'vfletcher3');
insert into Company (CompID, CompName, PostalCode, username) values (5, 'Luettgen, Greenholt and Will', 'K0A 0C9', 'ameffin4');
insert into Company (CompID, CompName, PostalCode, username) values (6, 'Schroeder-Quigley', 'G0N 1C0', 'abaigent5');
insert into Company (CompID, CompName, PostalCode, username) values (7, 'Ullrich-Casper', 'J0M 1T0', 'baberhart6');
insert into Company (CompID, CompName, PostalCode, username) values (8, 'Stanton, Rohan and Bergstrom', 'E1G 3K2', 'dradeliffe7');
insert into Company (CompID, CompName, PostalCode, username) values (9, 'Conroy Group', 'G0K 1P0', 'shelian8');
insert into Company (CompID, CompName, PostalCode, username) values (10, 'Hilll Group', 'C0A 1G0', 'ishearstone9');
insert into Company (CompID, CompName, PostalCode, username) values (11, 'Prohaska LLC', 'G0W 2V0', 'sgooderea');
insert into Company (CompID, CompName, PostalCode, username) values (12, 'Pollich-Hane', 'X0A 0A9', 'hsclaterb');
insert into Company (CompID, CompName, PostalCode, username) values (13, 'Mills, Miller and Olson', 'E1H 0H7', 'cmayowc');
insert into Company (CompID, CompName, PostalCode, username) values (14, 'Durgan-Blanda', 'G0C 0E2', 'rlandord');
insert into Company (CompID, CompName, PostalCode, username) values (15, 'Ryan-Morar', 'X0C 0H0', 'kbroadye');
insert into Company (CompID, CompName, PostalCode, username) values (16, 'Auer, Wilderman and McLaughlin', 'A0A 0A7', 'edudhillf');
insert into Company (CompID, CompName, PostalCode, username) values (17, 'Kuphal-Fahey', 'A0A 0B2', 'hgoningg');
insert into Company (CompID, CompName, PostalCode, username) values (18, 'Collier LLC', 'J0J 0C2', 'ssilwoodh');
insert into Company (CompID, CompName, PostalCode, username) values (19, 'Hermann-Cole', 'X0E 0V0', 'abonnori');
insert into Company (CompID, CompName, PostalCode, username) values (20, 'Beatty, Mueller and Luettgen', 'J0N 0A6', 'sbunnj');

