insert into Company (CompID, CompName, PostalCode, username) values (1, 'Dooley, Conn and Mertz', 'T0A 0B6', 'loffiler0');
insert into Company (CompID, CompName, PostalCode, username) values (2, 'Jakubowski, Lesch and Romaguera', 'X0A 0A0', 'lebertz1');
insert into Company (CompID, CompName, PostalCode, username) values (3, 'Luettgen-Gottlieb', 'K0A 0A3', 'wcasazza2');
insert into Company (CompID, CompName, PostalCode, username) values (4, 'Keebler Inc', 'G0X 0C2', 'vfletcher3');
insert into Company (CompID, CompName, PostalCode, username) values (5, 'Cormier Group', 'H3X 2V4', 'ameffin4');
insert into Company (CompID, CompName, PostalCode, username) values (6, 'Collier Inc', 'R0A 0C8', 'abaigent5');
insert into Company (CompID, CompName, PostalCode, username) values (7, 'Blick LLC', 'J2L 0A3', 'baberhart6');
insert into Company (CompID, CompName, PostalCode, username) values (8, 'Strosin-Johns', 'K0A 1P0', 'dradeliffe7');
insert into Company (CompID, CompName, PostalCode, username) values (9, 'Ruecker-Boyer', 'G0G 0C6', 'shelian8');
insert into Company (CompID, CompName, PostalCode, username) values (10, 'Morissette, Koch and Nicolas', 'J0H 0A2', 'ishearstone9');
insert into Company (CompID, CompName, PostalCode, username) values (11, 'Baumbach-Lesch', 'R0A 0M0', 'sgooderea');
insert into Company (CompID, CompName, PostalCode, username) values (12, 'Tillman, Dooley and Rodriguez', 'G0G 0G0', 'hsclaterb');
insert into Company (CompID, CompName, PostalCode, username) values (13, 'Runte, Schaden and Kling', 'J8L 0E4', 'cmayowc');
insert into Company (CompID, CompName, PostalCode, username) values (14, 'Wolff, D''Amore and Weimann', 'J0B 3B0', 'rlandord');
insert into Company (CompID, CompName, PostalCode, username) values (15, 'Wolff-Bode', 'G0N 1C0', 'kbroadye');
insert into Company (CompID, CompName, PostalCode, username) values (16, 'Emard Group', 'G0L 0A3', 'edudhillf');
insert into Company (CompID, CompName, PostalCode, username) values (17, 'Wilderman Group', 'J8C 0C1', 'hgoningg');
insert into Company (CompID, CompName, PostalCode, username) values (18, 'Russel, Nicolas and Kuhlman', 'J0E 2L0', 'ssilwoodh');
insert into Company (CompID, CompName, PostalCode, username) values (19, 'Kreiger Inc', 'J2L 0A3', 'abonnori');
insert into Company (CompID, CompName, PostalCode, username) values (20, 'Kohler and Sons', 'T0A 0A4', 'sbunnj');
